#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Partsly.Resource", IsApplication=true)]

namespace Partsly
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::Partsly.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::Partsly.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::Partsly.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int barcode = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher_APP = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int CheckInButton = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int CheckOutButton = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int barcodeImageView = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int buttonBack = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int buttonQtyCheckout = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int buttonQtyScan = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int buttonQuickCheckout = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int buttonQuickScan = 2131099649;
			
			// aapt resource value: 0x7f06000a
			public const int contentFrame = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int textView2 = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Checkin = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Checkout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int zxingscanneractivitylayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int zxingscannerfragmentlayout = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int beep = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int camera_swap_icon = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int camera_swap_icon_pressed = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int flashlight_turn_off_icon = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int flashlight_turn_off_icon_pressed = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int flashlight_turn_on_icon = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int flashlight_turn_on_icon_pressed = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int ic_btn_search = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int ocr_turn_off_icon = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int ocr_turn_on_icon = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int scan_line_blue = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int scan_line_white = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int scandit_logo = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int scandit_logo2x = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int scandit_logo3x = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int scandit_tracking_logo = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int scandit_tracking_logo2x = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int scandit_tracking_logo3x = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int tracking_beep = 2130968594;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int scanHistory = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int version = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
